spring.application.name=sample_project

# server port Number
server.port=80

### oracle setting ###
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521:xe
spring.datasource.username=spring_boot_practice
spring.datasource.password=1234

### MySQL settings ###
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_practice
# spring.datasource.username=spring_boot_practice
# spring.datasource.password=1234

# jsp setting
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# mybatis setting
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=kr.or.iei.*.model.vo
mybatis.configuration.jdbc-type-for-null=NULL

# file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
